### ISSUE TITLE
ircddbgateway config file

### ISSUE THREAD

**Issue by iw0red** [g4klx/ircDDBGateway#17]
Hi all, I installed the ircddbgateway from the scratch. I'm looking for the configuration file. The ircddbgatewayconfig program requires the GUI that I can't have.
Thanks in advance,
73 Marco IW0RED.

**Comment by iw0red** [comment]
Thanks!
73 Marco IW0RED.

**Comment by AndyTaylorTweet** [comment]
This probably isn't perfect, but it should be enough to get you started;


gatewayType=1
gatewayCallsign=M1ABC
gatewayAddress=0.0.0.0
icomAddress=172.16.0.20
icomPort=20000
hbAddress=127.0.0.1
hbPort=20010
latitude=0.00
longitude=0.00
description1=Town, L0C4T0R
description2=Country
url=
repeaterCall1=M1ABC
repeaterBand1=B
repeaterType1=0
repeaterAddress1=127.0.0.1
repeaterPort1=20011
reflector1=REF001 C
atStartup1=1
reconnect1=0
frequency1=438.80000
offset1=0.0000
rangeKms1=1.000
latitude1=0.0
longitude1=0.0
agl1=3.000
description1_1=Town, L0C4T0R
description1_2=Country
url1=
band1_1=0
band1_2=0
band1_3=0
repeaterCall2=
repeaterBand2= 
repeaterType2=0
repeaterAddress2=127.0.0.1
repeaterPort2=20012
reflector2=
atStartup2=0
reconnect2=0
frequency2=0.00000
offset2=0.0000
rangeKms2=0.000
latitude2=0.000000
longitude2=0.000000
agl2=0.000
description2_1=
description2_2=
url2=
band2_1=0
band2_2=0
band2_3=0
repeaterCall3=
repeaterBand3= 
repeaterType3=0
repeaterAddress3=127.0.0.1
repeaterPort3=20013
reflector3=
atStartup3=0
reconnect3=0
frequency3=0.00000
offset3=0.0000
rangeKms3=0.000
latitude3=0.000000
longitude3=0.000000
agl3=0.000
description3_1=
description3_2=
url3=
band3_1=0
band3_2=0
band3_3=0
repeaterCall4=
repeaterBand4= 
repeaterType4=0
repeaterAddress4=127.0.0.1
repeaterPort4=20014
reflector4=
atStartup4=0
reconnect4=0
frequency4=0.00000
offset4=0.0000
rangeKms4=0.000
latitude4=0.000000
longitude4=0.000000
agl4=0.000
description4_1=
description4_2=
url4=
band4_1=0
band4_2=0
band4_3=0
ircddbEnabled=1
ircddbHostname=rr.openquad.net
ircddbUsername=M1ABC
ircddbPassword=
ircddbEnabled2=0
ircddbHostname2=group1-irc.ircddb.net
ircddbUsername2=
ircddbPassword2=
ircddbEnabled3=0
ircddbHostname3=
ircddbUsername3=
ircddbPassword3=
ircddbEnabled4=0
ircddbHostname4=
ircddbUsername4=
ircddbPassword4=
aprsEnabled=1
aprsPassword=00000
aprsHostname=euro.aprs2.net
aprsPort=14580
dextraEnabled=1
dextraMaxDongles=5
dplusEnabled=1
dplusMaxDongles=5
dplusLogin=M1ABC
dcsEnabled=1
ccsEnabled=1
ccsHost=CCS706
xlxEnabled=0
xlxOverrideLocal=0
xlxHostsFileUrl=
starNetBand1=B
starNetCallsign1=
starNetLogoff1=
starNetInfo1=
starNetPermanent1=
starNetUserTimeout1=
starNetGroupTimeout1=
starNetCallsignSwitch1=1
starNetTXMsgSwitch1=1
starNetReflector1=
starNetBand2=B
starNetCallsign2=
starNetLogoff2=
starNetInfo2=
starNetPermanent2=
starNetUserTimeout2=
starNetGroupTimeout2=
starNetCallsignSwitch2=1
starNetTXMsgSwitch2=1
starNetReflector2=
starNetBand3=A
starNetCallsign3=        
starNetLogoff3=        
starNetInfo3=
starNetPermanent3=        
starNetUserTimeout3=
starNetGroupTimeout3=
starNetCallsignSwitch3=0
starNetTXMsgSwitch3=1
starNetReflector3=
starNetBand4=A
starNetCallsign4=        
starNetLogoff4=        
starNetInfo4=
starNetPermanent4=        
starNetUserTimeout4=
starNetGroupTimeout4=
starNetCallsignSwitch4=0
starNetTXMsgSwitch4=1
starNetReflector4=
starNetBand5=A
starNetCallsign5=        
starNetLogoff5=        
starNetInfo5=
starNetPermanent5=        
starNetUserTimeout5=
starNetGroupTimeout5=
starNetCallsignSwitch5=0
starNetTXMsgSwitch5=1
starNetReflector5=
remoteEnabled=1
remotePassword=password
remotePort=10022
language=0
infoEnabled=1
echoEnabled=1
logEnabled=1
dratsEnabled=1
dtmfEnabled=1
mobileGPSEnabled=0
mobileGPSAddress=127.0.0.1
mobileGPSPort=7834
windowX=-1
windowY=-1
