### ISSUE TITLE
ircDDBGateway similar to YSF, NXDN... gateways

### ISSUE THREAD

**Issue by f4exb** [g4klx/ircDDBGateway#2]
This issue is opened to request a version of ircDDBGateway that works similarly to YSFGateway or NXDNGateway simply with a .ini file and no GUI. This would help a lot with setting up headless configurations. Moreover it uses a lot of files with fixed locations that are root only access which is a pain. It should be made configurable as with the other gateways. Many thanks in advance for considering this!

**Comment by g4klx** [comment]
I looked into this, and it a huge piece of work. Moving away from wxWidgets and removing some of the functionality took me over two weeks and I still wasn't finished. Also the testing would have been a nightmare. I think I have enough work to do as it is!

**Comment by AndyTaylorTweet** [comment]
@f4exb you can modify the file locations in the Makefile;
You don't need the GUI, ircddbgatewayd runs with no GUI, I posted a sample config in #17 that you can take a look at.

Hope that helps.
