### ISSUE TITLE
Issues with DCS014 in DCS_Hosts.txt

### ISSUE THREAD

**Issue by vk4jlm** [g4klx/ircDDBGateway#22]
While diagnosing an issue someone was having linking to DCS014 in the last few days, I observed that the address for DCS014 in the latest DCS_Hosts.txt within this repository is wrong, because it points to a different IP address that doesn't match the official dcs014.xreflector.net DNS A Record.

As the Sysop of DCS014 I can confirm that the correct IP address is 52.63.223.130 which hasn't changed since September 2016, the DCS_Hosts.txt was was correct in this repository pointing to "dcs014.xreflector.net" until the latest update to the host file on the 09/01/19.

Can the change please be reverted so it points to dcs014.xreflector.net, ensuring it is correct in the repository and people building from source are able to connect "out of the box"?

As a reference point the entries for DCS014 are correct in the Pi-Star generated DCS_Hosts.txt here: http://www.pistar.uk/downloads/DCS_Hosts.txt so I'm not sure where the incorrect entry is coming from.

Thanks,

VK4JLM

**Comment by g4klx** [comment]
Done

**Comment by vk4jlm** [comment]
Thank you
