### ISSUE TITLE
Dplus link to a repeater re-links every 29 secs

### ISSUE THREAD

**Issue by moiei** [g4klx/ircDDBGateway#25]
I guess this is related with the G2 NAT_TRAVERSAL thing.
If you link to a repeater with the command ED1xxxCL. It links (voice says "connected to ED..."), but every 29 secs you get again the message "connected to ED..."

When you launch ircddbgateway , the screen display the load of DPLUS addresses, and after a while, I get the message:
`Registered with auth.dstargateway.org using callsign M0IEI`
And a bit later
`Error: Cannot connect the TCP client socket, err=111`

Can this g2 hole punch thing be disabled and made optional?
I have tried with the CFlags without success.

Any clue will be truly appreciated
73 de Pedro

**Comment by g4klx** [comment]
It looks like the packets from the reflector aren't being received at the gateway. This is typically a firewall/router issue. You need to look at the data going in and out with something like WireShark in order to see what is happening.

**Comment by moiei** [comment]
I have done more tests. I setup ircddbgateway in my private server in Spain (different router, ISP provider, etc) and DstarRepeater running in the UK. They can communicate -ports do not look like a problem- and ircddbgateway gets the exactly same TCP err 111  at the time the connection is stablished with the target reflector.
`M: 2019-02-09 18:37:16: Link command from M0IEI  C to ED1ZAE C issued via UR Call by M0IEI
M: 2019-02-09 18:37:16: D-Plus reply is OKRW
M: 2019-02-09 18:37:16: D-Plus ACK message received from ED1ZAE C
M: 2019-02-09 18:37:16: D-Plus link to ED1ZAE C established
E: 2019-02-09 18:37:20: Cannot connect the TCP client socket, err=111`

**Comment by moiei** [comment]
Update:
Three routers. Switched to fixed IP with the ISP provider. Same result
Please, can anybody confirm that DPLUS linking is working with a fresh compilation?

**Comment by moiei** [comment]
Solved: It seems that my callsign is locked out in the US-Trust servers. I have no idea why. Never received any mail about misuse.
