### ISSUE TITLE
Minimum requirements of wxwidgets

### ISSUE THREAD

**Issue by DL4OCH** [g4klx/ircDDBGateway#4]
As I am using a Raspberry with Debian Stretch,
is it possible to list the required libraries and tools to compile ircDDBGateway?

Almost everything compiles fine with 

wxgtk3.0
wx-common
libwxbase3.0-dev

installed. But GUI.common creates errors which aborts the entire process.

Also a no-gui Makefile would make life much easier.

Thanks in advance for investigating,
 Wilm, DL4OCH

**Comment by g4klx** [comment]
I think you should be able to do:

$ make ircDDBGateway/ircddbgatewayd

Which should just build the non-GUI gateway without anything else, particularly the config program which always uses a GUI.

**Comment by DL4OCH** [comment]
Works ! Thanks Jonathan.

Is there a way to compile a -no-gui version of timeserverd as well ? 
I'll steal the config-files from an older version and will see, if all works

**Comment by DL4OCH** [comment]
As it didn't did, what I've expected i've compiled it for Raspberry Pi 3 without any problems and without wxwidgets to be compiles from scratch.

I've just installed GTK 3.0 with 'apt-get install gtk3.0'

After approx. 30 minutes the entire package has been compiled without any error.
