### ISSUE TITLE
TimeServer app is not compiling with GUI

### ISSUE THREAD

**Issue by EA1JM** [g4klx/ircDDBGateway#9]
Hello John, I have compiled the new ircDDBGateway with the instructions sudo make -f MakefileGUI and sudo make -f MakefileGUI install and seems that only the daemon version of TimeServer is compiled, could you check if it is normal? It would be nice to use the Timeserver with the GUI as well, thanks!

make[1]: se entra en el directorio '/home/pi/ircDDBGateway/TimeServer'
install -g bin -o root -m 0775 timeserverd "/usr/bin"
make[1]: se sale del directorio '/home/pi/ircDDBGateway/TimeServer'

It only compiles and installs the daemon although I have used the GUI makefile.

**Comment by g4klx** [comment]
I've fixed it now. When compiled with the MakefileGUI, you'll get all of the programs with the GUI compiled also. I hope that helps.

**Comment by EA1JM** [comment]
Many thanks John! Congrats for your excellent work in the ham radio community!
